INCLUDE "header.inc"

CONT   EQU 0X0A
RET_1M EQU 0X0B
RET_1S EQU 0X0C
MOVLW	0XFF
MOVWF	TRISA
MOVLW	0X00
MOVWF	TRISB
 
GOTO	OPCION_0

;Retardo de 1 milisegundo
R_1S    MOVLW   d'1000'
	MOVWF   RET_1S

R_1M    MOVLW   d'498' ;1CM
        MOVWF   RET_1M ;1CM
LAZO    NOP
	DECFSZ  RET_1M
	BRA	LAZO
	DECFSZ  RET_1S
	BRA	R_1M
	RETURN
 
TABLA	ADDWF	PCL, 1
	RETLW	0X3F ;0
	RETLW	0X06 ;1
	RETLW	0X5B ;2
	RETLW	0X4F ;3
	RETLW	0X66 ;4
	RETLW	0X6D ;5
	RETLW	0X7D ;6
	RETLW	0X07 ;7
	RETLW	0X7F ;8
	RETLW	0X67 ;9
	RETLW	0X77 ;A
	RETLW	0X7C ;b
	RETLW	0X39 ;C
	RETLW	0X5E ;d
	RETLW	0X79 ;E
	RETLW	0X71 ;F
	
CONT_DEC_ASC	CLRF	CONT
DESPLIEGA_DEC	MOVF	CONT, 0
		CALL	TABLA
		MOVWF	PORTB
		CALL	LAZO
		INCF	CONT, 1
		INCF	CONT, 1
		MOVF	CONT, 0
		SUBLW	0X14
		BTFSS	STATUS, Z
		GOTO	DESPLIEGA_DEC
		GOTO	OPCION_0

CONT_HEX_PARES	CLRF	CONT
DESPLIEGA_HEX	MOVF	CONT, 0
		CALL	TABLA
		MOVWF	PORTB
		CALL	LAZO
		INCF	CONT, 1
		INCF	CONT, 1
		INCF	CONT, 1
		INCF	CONT, 1
		MOVF	CONT, 0
		SUBLW	0X20
		BTFSS	STATUS, Z
		GOTO	DESPLIEGA_HEX
		GOTO	OPCION_0

		
CONT_OCT_DESC	CLRF	CONT
DESPLIEGA_OCT	MOVF	CONT, 0
		CALL	TABLA
		MOVWF	PORTB
		CALL	LAZO
		INCF	CONT, 1
		INCF	CONT, 1
		MOVF	CONT, 0
		SUBLW	0X10
		BTFSS	STATUS, Z
		GOTO	DESPLIEGA_OCT
		GOTO	OPCION_0

RESET_M	    MOVLW   0X00
	    MOVWF   PORTB
	    GOTO    OPCION_0
	
OPCION_0    MOVF    PORTA, 0
	    SUBLW   0X00
	    BTFSS   STATUS, Z
	    GOTO    OPCION_1
	    GOTO    CONT_DEC_ASC

OPCION_1    MOVF    PORTA, 0
	    SUBLW   0X01
	    BTFSS   STATUS, Z
	    GOTO    OPCION_2
	    GOTO    CONT_HEX_PARES

OPCION_2    MOVF    PORTA, 0
	    SUBLW   0X02
	    BTFSS   STATUS, Z
	    GOTO    OPCION_3
	    GOTO    CONT_OCT_DESC
	   
OPCION_3    MOVF    PORTA, 0
	    SUBLW   0X03
	    BTFSS   STATUS, Z
	    GOTO    OPCION_0
	    GOTO    RESET_M
END